---
- name: installatalion du filer   
  hosts: FILER
  remote_user: root
  vars:
    user: automate
    remote_host: "{{ remotehosts.stdout }}"
    remote_ip: "{{ ansible_default_ipv4.address }}"
    dc_name: "myworldcompany"
    ex_name: "net"
    dc_ip: "10.0.1.2"
  vars_prompt:
   - name: "password_dc"
     prompt: "Entrer le mot de passe du DC"
     private: yes 

  pre_tasks:

  - name: lire le fichier host
    command: cat /etc/hostname
    register: remotehosts

  - name: viewing contents
    debug:
      msg: "{{ansible_default_ipv4.address}}" 

  roles:
  - role: debianad
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ununtu'
  - role: centosad
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Entreprrise Linux'
  - role: communad
  - role: servicead 
