---
- name: preparation pour centos
  yum:
    update_cache: yes
    pkg:
      - libselinux-python
      - samba-common
      - samba-common-tools
      - samba-winbind-clients
      - nano
      - krb5-workstation
    state: present

- name: activation repo epel
  yum:
    pkg:
      - epel-release
    state: present

- name: installation de pip
  yum:
    pkg: python-pip
    state: present
  

- name: installlation de pexpect
  pip:
    name:
        - pexpect
        - ldap3


- name: modification du groupmap
  #shell:
  command: net -s /dev/null groupmap add sid=S-1-5-32-546 unixgroup=nobody type=builtin
  ignore_errors: yes


- name: modification de ulimit
  shell:
     cmd: ulimit -n 16384
