---

#    - name: copie de smb.conf
#      copy:
#       src: /etc/ansible/files/smb.conf
#       dest: /etc/samba/
#       owner: root
#       group: root
#       mode: 0644

    - name: copie de krb5
      copy: 
       src: /etc/ansible/files/krb5.conf
       dest: /etc/
       owner: root
       group: root
       mode: 0644


    - name: copie de nsswitch
      copy:
       src: /etc/ansible/files/nsswitch.conf
       dest: /etc/
       owner: root
       group: root
       mode: 0644

    - name: creation des repertoires filer
      file:
       path: /home/partage
       state: directory
       owner: root
       group: users
       mode: '0777'

    - name: home file
      file:
       path: /home/MYWORLDCOMPANY
       state: directory
       owner: root
       group: users
       mode: '0777'


    - name: creation du ticket kerberos
      expect:
        command: kinit administrateur
        responses:
         (?i)password: "{{ password_dc }}"
      no_log: False 


    - name: Ajout du serveur au DC
      expect:
        command: net join -U administrateur
        responses:
          password: "{{ password_dc }}" 



    - name: Creation des Homes
      users_ad:
        ad_name: automate
        ad_password: Password.
        ad_dc_name: MYWORLDCOMPANY
        ad_serveur_ip: 10.0.1.2

