---
    - template:
       src: /etc/ansible/templates/hosts.j2
       dest: /etc/hosts

    - template:
       src: /etc/ansible/templates/resolv.j2
       dest: /etc/resolv.conf

    - template:
       src: /etc/ansible/templates/smb.j2
       dest: /etc/samba/smb.conf


    - template:
       src: /etc/ansible/templates/krb5.j2
       dest: /etc/krb5.conf
   

    - name: copie de nsswitch
      copy:
       src: /etc/ansible/files/nsswitch.conf
       dest: /etc/
       owner: root
       group: root
       mode: 0644

    - name: creation des repertoires filer
      file:
       path: /home/partage
       state: directory
       owner: root
       group: users
       mode: '0777'

    - name: home file
      file:
       path: /home/MYWORLDCOMPANY
       state: directory
       owner: root
       group: users
       mode: '0777'


    - name: creation du ticket kerberos
      expect:
        command: kinit administrateur
        responses:
         (?i)password: "{{ password_dc }}"
      no_log: False 


    - name: Ajout du serveur au DC
      expect:
        command: net join -U administrateur
        responses:
          password: "{{ password_dc }}" 



    - name: Creation des Homes
      users_ad:
        ad_name: administrateur
        ad_password: "{{ password_dc }}"
        ad_dc_name: "{{ dc_name|upper }}"
        ad_serveur_ip: "{{ dc_ip }}"

